icr_server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('icr/', include(('webserver.urls', 'webserver'), namespace='webserver'))
]

# checks whether we in development mode or not
if settings.DEBUG:
    # add media files. Do not use in production
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # for developmend mode only!

webserver/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('templates/', ListTemplateView.as_view(), name='list_template_view'),
    path('upload/', UploadFileView.as_view(), name='upload_file_view'),
    path('download_csv/', DownloadFileCsvView.as_view(), name='download_file_csv_view'),
    path('download_json/', DownloadFileJsonView.as_view(), name='download_file_json_view')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webserver/models/company.py
from django.db import models


class Company(models.Model):
    max_length_company_name = 50

    name = models.CharField('name', max_length=max_length_company_name)

    def __str__(self):
        return self.name

webserver/models/field_coordinate.py
from django.db import models


class FieldCoordinate(models.Model):
    x = models.IntegerField('x', help_text='Top left x box coordinate')
    y = models.IntegerField('y', help_text='Top left x box coordinate')
    width = models.IntegerField('width', help_text='width of the box')
    height = models.IntegerField('height', help_text='height of the box')

    def get_coordinates(self) -> tuple:
        return self.x, self.y, self.width, self.height

webserver/models/file_template.py
import os

from django.db import models


# Create your models here.
class FileTemplate(models.Model):
    description_max_len = 50

    file = models.FileField(upload_to='templates/')
    description = models.CharField(
        'description',
        max_length=description_max_len,
        null=True,
        blank=True
    )
    company_name = models.ForeignKey('Company', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.file.name} - {self.description}'

    def get_path(self):
        return self.file.url

    def get_locations_list(self) -> list:
        locations = list([element.get_location_tuple() for element in self.location_set.all()])
        return locations

webserver/models/keyword.py
from django.db import models


class Keyword(models.Model):
    keyword_max_len = 100

    keyword = models.CharField('keyword', max_length=keyword_max_len)
    to_location = models.ForeignKey('Location', on_delete=models.CASCADE)

webserver/models/location.py
from django.db import models
from typing import List, Tuple

from .file_template import FileTemplate
from .field_coordinate import FieldCoordinate
from .keyword import Keyword
from ai.config import OCRLocation


class LocationManager(models.Manager):

    def create_location(self, template: FileTemplate, location: tuple, description: str = None):
        coordinate_entity = FieldCoordinate(
            x=location.bbox[0],
            y=location.bbox[1],
            width=location.bbox[2],
            height=location.bbox[3]
        )
        coordinate_entity.save()
        location_entity = Location(
            id=location.id,
            coordinates=coordinate_entity,
            to_template=template,
            description=description,
        )
        location_entity.save()
        for keyword in location.filter_keywords:
            keyword_entity = Keyword(
                keyword=keyword,
                to_location=location_entity
            )
            keyword_entity.save()
        return location


class Location(models.Model):
    id_max_len = 100

    id = models.CharField('id', max_length=id_max_len, primary_key=True)
    coordinates = models.ForeignKey(FieldCoordinate, on_delete=models.CASCADE)
    to_template = models.ForeignKey(FileTemplate, on_delete=models.CASCADE)

    description = models.CharField(
        'description',
        max_length=id_max_len,
        help_text="Just to know for which template this location is",
        null=True,
        blank=True
    )

    objects = LocationManager()

    def get_location_tuple(self):
        keywords = list(self.keyword_set.all().values_list('keyword', flat=True))
        coord = self.coordinates.get_coordinates()
        return OCRLocation(self.id, coord, keywords)

webserver/models/uploaded_photo.py
from django.db import models
from ..models import FileTemplate


class UploadedPhoto(models.Model):
    photo = models.FileField(upload_to='media/')
    template = models.ForeignKey(FileTemplate, on_delete=models.CASCADE)

    def __str__(self):
        return self.photo.name

    def get_path(self):
        return self.photo.path

webserver/forms/upload_form.py
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

webserver/views/base_view.py
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status


class BaseView(APIView):
    def error_response(self, errors, status_code=status.HTTP_400_BAD_REQUEST):
        return Response(data=errors, status=status_code)

    def success_response(self, data, status_code=status.HTTP_200_OK):
        return Response(data=data, status=status_code)

webserver/views/choise_of_result_view.py
from django.shortcuts import render
from django.views.generic import TemplateView
from ai.file_saver import file_saver


class ChoiseOfResultView(TemplateView):
    def post(self, request, *args, **kwargs):
        choices = request.POST.getlist('list')
        file_saver(choices)
        print(choices)
        context = {'choices': choices}
        return render(request, template_name='upload.html', context=context)

webserver/views/download_file_csv_view.py
from .download_file_view import DownloadFileView
from ..serializers.json_data_serializer import JsonDataSerializer
import json


class DownloadFileCsvView(DownloadFileView):
    serializer_class = JsonDataSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            json_str = json.dumps(serializer.data.get('data'))
            path = 'results.csv'
            content_type = 'text/csv'
            return super().get_file(request, json_str, path, content_type, *args, **kwargs)
        return self.error_response(errors=serializer.errors)

webserver/views/download_file_json_view.py
from .download_file_view import DownloadFileView


class DownloadFileJsonView(DownloadFileView):
    def get(self, request, *args, **kwargs):
        path = 'results.json'
        content_type = 'application/json'
        return super().get_file(request, path, content_type, *args, **kwargs)

webserver/views/download_file_view.py
from django.http import HttpResponse

from .base_view import BaseView


class DownloadFileView(BaseView):
    def get_file(self, request, json: str, path: str, content_type: str, *args, **kwargs):
        response = HttpResponse(json, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename=' + path
        return response

webserver/views/list_template_view.py
from django.shortcuts import render

from ..models import FileTemplate
from rest_framework.generics import ListAPIView

from ..serializers import FileTemplateSerializer


class ListTemplateView(ListAPIView):
    queryset = FileTemplate.objects.all().order_by('id')
    serializer_class = FileTemplateSerializer

webserver/views/upload_file_view.py
from rest_framework import status
from ..models import UploadedPhoto, FileTemplate
from ai.ocr_form import run
from .base_view import BaseView
from rest_framework.generics import ListCreateAPIView
from ..serializers import UploadFileSerializer, FileTemplateSerializer
import os
from webserver.helpers import from_base64_to_content_file


class UploadFileView(BaseView, ListCreateAPIView):
    serializer_class = FileTemplateSerializer
    post_serializer = UploadFileSerializer
    queryset = FileTemplate.objects.all()

    def post(self, request, *args, **kwargs):
        try:
            serializer = self.post_serializer(data=request.data)
            if serializer.is_valid():
                uploaded_file = from_base64_to_content_file(request.data.get('photo'), filename='file')
                template_id = request.data.get('template')
                template_file = FileTemplate.objects.get(id=template_id)
                photo = UploadedPhoto(photo=uploaded_file, template=template_file)
                data = run(
                    par_template_file=template_file.file.file,
                    par_image_file=photo.photo.file,
                    par_locations=template_file.get_locations_list(),
                )
                return self.success_response(data=data, status_code=status.HTTP_201_CREATED)
            else:
                return self.error_response(errors=serializer.errors)

        except Exception as e:
            raise e

webserver/templates/find_coordinates.html
<html>
    <head>
        <title>Image Processs</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-jcrop/0.9.15/css/jquery.Jcrop.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-jcrop/0.9.15/js/jquery.Jcrop.js"></script>
        </head>
    <body>
        <!-- Insert your image path here-->
        <img src="antrag-1.png" alt="" id="image">
        <script>
            $(document).ready(function(){
                $('#image').Jcrop({
                    onSelect: function(c){
                        console.log(c);

                        console.log(c.x);
                        console.log(c.y);
                        console.log(c.w);
                        console.log(c.h);
                    }
                })
            })
        </script>
    </body>    
    </html>

webserver/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% for template in templates %}
    <li>{{ template.id }} - {{ template.file.name }}</li>
    {% endfor %}
    {% for up in upload %}
    <li>{{ up.id }} - {{up.photo_name.name}}</li>
    {% endfor %}

</ul>
</body>
</html>

webserver/templates/upload.html
{% block content %}

<h3>Templates we have</h3>
{% for template in templates %}
<li>{{ template.id }} - {{ template }}</li>
{% endfor %}

<h2> Upload </h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="template_id">Template ID:</label>
    <input type="text" id="template_id" name="template_id"><br><br>

    <input type="checkbox" id="printed" name="printed" value="printed">
    <label for="printed"> Printed </label><br>
    <input type="checkbox" id="handwritten" name="handwritten" value="handwritten">
    <label for="handwritten"> Handwritten </label><br>

    <input type="file" name="document">
    <button type="submit">Upload File</button>
    <a href="{% url 'webserver:download_file_json_view' %}">Download JSON-File</a>
    <a href="{% url 'webserver:download_file_csv_view' %}">Download CSV-File</a>
</form>
{% if url %}
<p>Uploaded File: <a href="{{ url }}"> {{ url }} </a></p>
{% endif %}
{% for key, value in message.items %}
<p> {{ key }} : {{ value }}
    {% endfor %}

    {% endblock %}